import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../components/Footer";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import NavBar from "../components/Navbar";
import Founders from "../components/Founders";
import Stats from "../components/Stats";
import Achievements from "../components/Acievements";
import Founders1 from "../components/Founders1";
// import TestimonialSlider from "../components/TestimonialSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Omega Study Center",
  description: "Generated by create turbo",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {/* <div className="text-red-500"> this is a div</div>   */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
